config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :treatments do
    resources :appointments, only: [ :new, :create ]
  end

  resources :appointments, only: [:show, :destroy, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :treatment

  validate :is_between_parent_period
  validates :date, :user, :treatment, presence: true

  private

  def is_between_parent_period
    unless date.between?(self.treatment.start_date, self.treatment.end_date)
      errors.add(:base, 'Falha ao marcar a consulta! Escolha uma data disponível!')
    end
  end
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  before_save :specialty_capitalize
  belongs_to :user
  has_many :appointments
  has_one_attached :photo
  validates :address, :start_date, :end_date, :specialty, :price, :user, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def specialty_capitalize
    self.specialty = self.specialty.capitalize
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :appointments
  has_many :treatments
  has_one_attached :avatar
  validates :first_name, :last_name, :email, :password, presence: true
  validates :email, uniqueness: true
  validates :first_name, uniqueness: { scope: :last_name, message: 'This name is already in use.' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :avatar])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :avatar])
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  # def new
  #   @treatment = Treatment.find(params[:treatment_id])
  #   @appointment = Appointment.new
  # end

  def index
    @appointments = Appointment.all
    # @appointments = Appointment.where(user_id: params[current_user.id])
  end

  def create
    @appointment = Appointment.new(appointment_params)
    @treatment = Treatment.find(params[:treatment_id])
    @appointment.treatment = @treatment
    @appointment.user = current_user
    if @appointment.save
      redirect_to appointment_path(@appointment), notice: "Sua consulta foi marcada!"
    else
      render 'treatments/show'
    end

  end

  def show
    @appointment = Appointment.find(params[:id])
  end

  def destroy
    @appointment = Appointment.find(params[:id])
    @appointment.destroy
    redirect_to appointments_path
  end

  private

  def appointment_params
    params.require(:appointment).permit(:date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @transparent = true
    @treatments = Treatment.all
    if params[:specialty]
      @treatments = @treatments.where(specialty: params[:specialty].capitalize)

    end
    @markers = @treatments.geocoded.map do |treatment|
      {
        lat: treatment.latitude,
        lng: treatment.longitude,
        info_window: render_to_string(partial: "info_window", locals: { treatment: treatment })
      }
    end
  end
end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController
  before_action :set_treatment, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: :show

  def index
    @treatments = current_user.treatments
  end

  def show
    @treatment = Treatment.find(params[:id])
    @appointment = Appointment.new
  end

  def new
    @treatment = Treatment.new
  end

  def create
    @treatment = Treatment.new(treatment_params)
    @treatment.user = current_user
    @treatment.save

    redirect_to treatments_path
  end

  def edit
    @treatment = Treatment.find(params[:id])
    @treatment.save
  end

  def update
    @treatment.update(treatment_params)

    redirect_to treatment_path(@treatment)
  end

  def destroy
    @treatment.destroy
    redirect_to treatments_path
  end

  private

  def treatment_params
    params.require(:treatment).permit(:address, :specialty, :start_date, :end_date, :price, :photo)
  end

  def set_treatment
    @treatment = Treatment.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/index.html.erb
<div class="container py-5 mt-5">
  <div class="row">
    <div class="col-12">
      <div class="treatment_container">
      <h2>Suas Consultas:</h2>
      <table class="table table-striped justify-content-center">
        <thead>
          <tr>
            <th>Especialidade</th>
            <th>Data da consulta</th>
            <th>Local</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% @appointments.each do |appointment| %>
          <tr>
            <td><%= appointment.treatment.specialty.capitalize %></td>
            <td><%= appointment.date %></td>
            <td><%= appointment.treatment.address %></td>
            <td>
              <%= link_to "Cancelar", appointment_path(appointment), method: 'DELETE', remote: true, class: "btn-medium" %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
      </div>
   </div>
  </div>
</div>

app/views/appointments/new.html.erb
<%# <div class="container">
  <h1>Consulta</h1>
  <%= simple_form_for [ @treatment, @appointment ] do |f| %>
    <%# <%= f.input :date %>
    <%# <%= f.submit "Marcar consulta", class: "btn-medium" %>
  <%# <% end %>
<%# </div> %>

app/views/appointments/show.html.erb
<div class="m-5">
  <div class="appointment-container container">
  <h2>Sua Consulta:</h2>
    <table class="table table-striped justify-content-center">
      <thead>
        <tr>
          <th>Especialidade</th>
          <th>Data da consulta</th>
          <th>Local</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @appointment.treatment.specialty.capitalize %></td>
          <td><%= @appointment.date %></td>
          <td><%= @appointment.treatment.address %></td>
        </tr>
      </tbody>
    </table>
  <h5>Você receberá um e-mail com os detalhes da sua consulta!</h5>
  <%= link_to 'Ver todas as consultas marcadas',  appointments_path(@appointments), class: 'btn btn-outline-dark' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Doctors4all</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/_info_window.html.erb
<h2><%= treatment.specialty %></h2>
<p><%= treatment.address %></p>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1624727828489-a1e03b79bba8);">
  <div class="container">
    <h1>Agende agora sua consulta</h1>
    <p><span data-controller="typed-js"></span></p>
    <div class="container">
      <div class="row">
        <div class="col">
          <%= form_tag root_path, method: :get do %>
            <div class="col mt-3 mb-2">
              <%= text_field_tag :specialty,
                                params[:specialty],
                                class: "form-control",
                                placeholder: "Especialidade"%>
            </div>
            <div class="col mt-3 mb-2">
              <%= submit_tag "Pesquisar", class: "btn-medium-border" %>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>
</div>


<div class="second-part">
  <div class="d-flex justify-content-around row treatment-flex">
    <% @treatments.each do |treatment| %>
      <div class="col-3 my-3">
        <div class="treatment-card">
          <div class="treatment-card-image" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= treatment.photo.attached? ? cl_image_path(treatment.photo.key) : 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?'%>)"></div>
          <div class="treatment-card-content p-3">
            <div class="d-flex justify-content-center treatment-card-title">
              <h4><%= treatment.specialty.capitalize %></h4>
            </div>
            <div class="m-0">
              <p><%= treatment.address %></p>
              <p><%= "R$ #{treatment.price}"%></p>
            </div>
            <div class="d-flex justify-content-center">
              <%= link_to "Detalhes", treatment_path(treatment), class: "btn-medium-branco" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <div style="width: 100%; height: 600px;" data-controller="mapbox" data-mapbox-markers-value="<%= @markers.to_json %>" data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1624727828489-a1e03b79bba8);">
  <div class="container">
    <h1>Agende agora sua consulta</h1>
    <p>Mais de 800 especialistas para te ajudar</p>
    <a class="btn btn-success" href="#">Agendar</a>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top <%="navbar-transparent" if @transparent%>" data-controller="navbar" data-action="scroll@window->navbar#updateNavbar">
  <div class="container-fluid">
      <%= link_to "#", class: "navbar-brand" do %>
        <p class="text-white" data-action="scroll@window->navbar#updateNavbar" data-navbar-target="p"><%= image_tag "https://www.baitadihospital.gov.np/storage/phpACjFrt.png" %> Doctors4All </p>
      <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto" data-action="scroll@window->navbar#updateNavbar">
        <% if user_signed_in? %>
          <li class="nav-item active" data-action="scroll@window->navbar#updateNavbar" data-navbar-target="li">
            <%= link_to "Home", root_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item" data-action="scroll@window->navbar#updateNavbar" data-navbar-target="li">
            <%= link_to "Oferte um Tratamento", new_treatment_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.avatar.attached? %>
              <%= cl_image_tag current_user.avatar.key, width: 50, height: 45, crop: :thumb, gravity: :face, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
               <% if current_user.appointments.any? %>
             <%= link_to "Suas consultas", "/appointments", class: "dropdown-item" %>
             <% end %>
              <% if current_user.treatments.any? %>
              <%= link_to "Seus tratamentos", "/treatments", class: "dropdown-item" %>
              <% end %>
              <%= link_to "Editar Perfil", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link text-white" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/treatments/edit.html.erb
<<<<<<< HEAD
<div class="appointment-container container py-5 mt-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white form-card p-3 shadow">
        <h4 class="text-center mt-3">Edite seu tratamento</h4>
        <%= simple_form_for @treatment do |f| %>
          <%= f.input :specialty, :label => "Especialidade", class: "form-control form-control-lg", type: "text" %>
          <%= f.input :price, :label => "Preço" %>
          <%= f.input :start_date, :label => "Data Inicial" %>
          <%= f.input :end_date, :label => "Data Final" %>
          <div class="text-center mt-5"><%= f.submit 'Salvar Alterações', class: 'btn-medium' %></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/treatments/index.html.erb
<div class="container py-5 mt-5">
  <div class="row">
    <div class="col-12">
      <div class="treatment_container">
      <h2>Seus tratamentos:</h2>
      <table class="table table-striped justify-content-center">
        <thead>
          <tr>
            <th>Especialidade</th>
            <th>Preço</th>
            <th>Disponibilidade</th>
            <th>Local</th>
            <th>Médico</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% @treatments.each do |treatment| %>
          <tr>
            <td><%= treatment.specialty %></td>
            <td>R$ <%= treatment.price %></td>
            <td><%= "De #{treatment.start_date} a #{treatment.end_date}" %></td>
            <td><%= treatment.address %></td>
            <td>
              <%# <button class="btn-medium" method="get" action="/treatments/:id/edit">Editar</button> %>
              <%= link_to "editar", edit_treatment_path(treatment[:id]), class: "btn-medium"%>
            </td>
            <td>
              <%# <button class="btn-medium">Deletar</button> %>
              <%= link_to "deletar", treatment_path(treatment), method: 'DELETE', remote: true, class: "btn-medium" %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
      </div>
   </div>
  </div>
</div>

app/views/treatments/new.html.erb
<div class="appointment-container container py-5 mt-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white form-card p-3 shadow">
        <h2>Criar um novo tratamento:</h2>
        <%= simple_form_for @treatment do |f| %>
          <%= f.input :specialty, :label => "Especialidade", class: "form-control form-control-lg", type: "text", placeholder: "Ex: Pediatria" %>
          <%= f.input :address, :label => "Endereço", placeholder: "Rua, n°, bairro, cidade" %>
          <%= f.input :price, :label => "Preço" %>
          <%= f.input :start_date, :label => "Data Inicial" %>
          <%= f.input :end_date, :label => "Data Final" %>
          <%= f.input :photo, as: :file, placeholder:"Image", :label => 'Image file:'%>
          <%= f.submit :create, :label => "Criar", class: 'btn-medium' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/treatments/show.html.erb
<div class="d-flex justify-content-around appointment-container container mb-3">
  <div class="row mt-5">
      <div class="treatment">
        <table class="table table-striped">
        <tbody>
          <tr>
            <th scope="row">Especialidade</th>
            <td><%= @treatment.specialty.capitalize %></td>
          </tr>
          <tr>
            <th scope="row">Preço da consulta</th>
            <td>R$ <%= @treatment.price %></td>
          </tr>
          <tr>
            <th scope="row">Médico</th>
            <td><%= "#{@treatment.user.first_name.capitalize} #{@treatment.user.last_name.capitalize}" %></td>
          </tr>
          <tr>
            <th scope="row">Endereço</th>
            <td><%= @treatment.address %></td>
          </tr>
          <tr>
            <th scope="row">Disponibilidade</th>
            <td>De <%= @treatment.start_date %> a <%= @treatment.end_date %></td>
          </tr>
        </tbody>
       </table>
     </div>
  </div>
  <div class="row">
    <div class="d-flex flex-column justify-content-around m-3 container mb-0">
      <% if @treatment.user == current_user %>
        <%= link_to 'Editar Tratamento',  edit_treatment_path(@treatment), class: 'btn btn-outline-secondary rounded-pill' %>
        <%= link_to 'Remover Tratamento', treatment_path(@treatment), method: 'DELETE', class: 'btn btn-outline-danger rounded-pill' %>
    </div>
      <% else %>
    <div class="d-flex justify-content-center align-items-center container">
      <div class="card-appointment py-5 px-3 shadow">
        <h4 class="text-center m-0">Marque sua consulta! </h4>
          <%= simple_form_for [ @treatment, @appointment ] do |f| %>
            <div class="d-flex flex-row mt-5"><%= f.input :date, label: 'Data:' %></div>
            <div class="text-center mt-5"><%= f.submit "Marcar consulta", class: "btn-medium-branco" %></div>
            <% @appointment.errors&.each do |attr, msg| %>
              <%= msg %>
            <% end %>
          <% end %>
      </div>
    </div>
    <% end %>
    </div>
</div>
</div>

<div class="d-flex justify-content-center container m-5">
    <%# <%= link_to 'Voltar', treatments_path, class: "btn-medium-branco" %>
  <%= link_to 'Procurar mais tratamentos', root_path, class: "btn-medium" %>
</div>